const catalogoMilo = [
    "1708",
    "3 PECADOS DESPUES…",
    "A VOS",
    "A1RE",
    "AEROBICO REMIX",
    "AL BORDE",
    "ALIOLI",
    "ALUMBRE",
    "ANTES DE LOS 20",
    "ASHE ASHE",
    "Al Sol",
    "Ama De Mi Sol",
    "BESAME (feat. Tiago PZK, Khea & Neo Pistea) - Remix",
    "Bajo De La Piel",
    "CARENCIAS DE CORDURA",
    "Carta de Despedida",
    "Cuando El Agua Hirviendo",
    "Cuando Estas Vos",
    "Cuando Ya Nadie Te Nombre",
    "DAÑA (ELVIRA)",
    "DESEO PERDER (INTERLUDIO)",
    "DIGAN",
    "DISPARA ***",
    "DOM1NGO",
    "El Bolero",
    "El Invisible",
    "FLA",
    "FLECHAZO EN EL CENTRO",
    "Fruto",
    "Gil",
    "HIPPIE",
    "I' AM",
    "Jangadero",
    "LA TOLA Y EL VELERO",
    "LA TORTURA",
    "LO QUE ME CAUSA",
    "La Canción Feliz Del Disco",
    "La Pucha Con el Hombre",
    "La Taleñita",
    "La Vida Era Más Corta",
    "Llora Llora",
    "Lucia",
    "Luciérnagas",
    "M.A.I",
    "MORNING",
    "Milagrosa",
    "Milo J: Bzrp Music Sessions, Vol. 57/66",
    "MmmM",
    "Morocha",
    "NI CARLOS NI JOSE",
    "NO HAGO TRAP",
    "NO MUCHO",
    "NO NO",
    "NUNCA VOY SOLO",
    "Niño",
    "No Estoy",
    "No Soy de Aquí, Ni Soy de Allá",
    "No soy Eterno",
    "OJALA",
    "OLIMPO",
    "PARAISO (daña)",
    "Pasos Al Costado",
    "Penas de Antaño",
    "RETIRADA",
    "Radamel",
    "Rara Vez",
    "Recordé",
    "Rincón",
    "SANGRE PARA DERRAMAR",
    "SINCERA TE",
    "Semillero",
    "Sessions #02",
    "Solifican12",
    "TE FUI A SEGUIR",
    "TOI HECHO",
    "TU MANTA",
    "Toy en el Mic",
    "Tu Paz",
    "Tus Vueltas",
    "UNA BALA",
    "VITALICIO",
    "Vainas",
    "Valores del West",
    "Vida De Rock",
    "Vudu",
    "buen día portación de rostro",
    "mi último peso"
];